apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: decathlon
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: decathlon
            image: atetelea/decathlon
          restartPolicy: OnFailure